run:
    cabal run weather

test match="":
    #!/bin/bash -e
    if [ -n "{{match}}" ]; then
        cabal test --test-options="--match {{match}}"
    else
        cabal test
    fi

verify:
    cabal build
    cabal test
    cabal run weather
