run:
    cabal run weather

test match="":
    #!/bin/bash -e
    if [ -n "{{match}}" ]; then
        cabal test --test-options="--match {{match}}"
    else
        cabal test
    fi

verify:
    ormolu --mode check $(find src app test -name '*.hs')
    cabal build
    cabal test
    cabal run weather

fix:
    ormolu --mode inplace $(find src app test -name '*.hs')

dependencies:
    cabal install ormolu
